// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/GoEnterpricePlatform/goEP-core/pkg/identity/roles/domain"
	"github.com/GoEnterpricePlatform/goEP-core/pkg/identity/tokens/claim"
	componentsIdentity "github.com/GoEnterpricePlatform/goEP-core/web/web-app/modules/identity/ui/components"
	"github.com/GoEnterpricePlatform/goEP-core/web/web-app/src/ui/components"
	"github.com/GoEnterpricePlatform/goEP-core/web/web-app/src/ui/layouts"
)

func RolesPermissionsPage(claims *claim.AccessTokenClaims, roles []*domain.Role) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.DashboardLayout(
			"roles-permissions",
			claims.Roles,
			claims.Permissions,
			RolesPermissionsContent(roles),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func RolesPermissionsContent(roles []*domain.Role) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-signals=\"{\r\n\t\t\trole_form: {\r\n\t\t\t\tid: '',\r\n\t\t\t\tname: '',\r\n\t\t\t},\r\n\t\t\tmodal: {\r\n\t\t\t\tdomain:'',\r\n\t\t\t\taction: '',\r\n\t\t\t},\r\n\t\t\terror: '',\r\n\t\t\tis_loading: false,\t\t\t\r\n\t\t}\"><section class=\"w-full\"><div class=\"mb-6 flex items-center justify-between gap-5\"><div><h1 class=\"text-2xl font-bold tracking-tight text-black\">Roles and permissions</h1><p class=\"mt-1.5 text-sm text-zinc-500\">Manage application roles and their permissions.</p></div></div><div class=\"flex justify-end mb-5\"><button type=\"button\" class=\"rounded-lg bg-black px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-zinc-800\" data-on:click=\"\r\n\t\t\t\t\t\t$role_form.id = '';\r\n\t\t\t\t\t\t$role_form.name = '';\r\n\r\n\t\t\t\t\t\t$error = '';\r\n\r\n\t\t\t\t\t\t$modal.domain = 'role';\r\n\t\t\t\t\t\t$modal.action = 'form';\r\n\t\t\t\t\t\">Create</button></div><div id=\"role-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = componentsIdentity.RoleList(roles).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ModalManager().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
